---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html/
    - mkdir -p $DEPLOYPATH/css $DEPLOYPATH/js $DEPLOYPATH/images/portfolio
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp membership.html $DEPLOYPATH
    - /bin/cp admin.html $DEPLOYPATH
    - /bin/cp css/* $DEPLOYPATH/css/
    - /bin/cp js/* $DEPLOYPATH/js/
    - /bin/cp images/hero.jpg $DEPLOYPATH/images/
    - /bin/cp images/portfolio/* $DEPLOYPATH/images/portfolio/
